# Generated by Django 5.1 on 2024-09-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_wallet_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionType',
            new_name='transactionType',
        ),
    ]
