# Generated by Django 5.1 on 2024-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='staus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='staus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varients',
            name='staus',
            field=models.BooleanField(default=True),
        ),
    ]
