# Generated by Django 5.1 on 2024-08-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0003_rename_staus_brand_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
    ]
