# Generated by Django 5.1 on 2024-08-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0005_rename_brand_brand_name_alter_products_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='adminManagements.products'),
        ),
    ]
