# Generated by Django 5.1 on 2024-08-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0008_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
