# Generated by Django 5.1 on 2024-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0009_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
