# Generated by Django 5.1 on 2024-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0010_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='croppedImage1',
            field=models.ImageField(blank=True, null=True, upload_to='media/cropedImage/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='croppedImage2',
            field=models.ImageField(blank=True, null=True, upload_to='media/cropedImage/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='croppedImage3',
            field=models.ImageField(blank=True, null=True, upload_to='media/cropedImage/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='croppedImage4',
            field=models.ImageField(blank=True, null=True, upload_to='media/cropedImage/'),
        ),
    ]
