# Generated by Django 5.1 on 2024-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0011_productimage_croppedimage1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='croppedImage1',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='croppedImage2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='croppedImage3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='croppedImage4',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
