# Generated by Django 5.1 on 2024-09-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0012_remove_productimage_croppedimage1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varients',
            name='imageId',
        ),
        migrations.AddField(
            model_name='products',
            name='imageId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminManagements.productimage'),
        ),
    ]
