# Generated by Django 5.1 on 2024-09-11 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0014_remove_products_imageid_varients_imageid'),
        ('shopping', '0010_remove_cartitem_product_remove_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refreshRate', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='imageId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminManagements.productimage'),
        ),
        migrations.AddField(
            model_name='products',
            name='resolution',
            field=models.IntegerField(default='324'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='refreshRate',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='adminManagements.refreshrate'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ForeignKey(default='432', on_delete=django.db.models.deletion.CASCADE, to='adminManagements.size'),
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
