# Generated by Django 5.1 on 2024-09-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0017_remove_products_refreshrate_remove_products_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refreshRate', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='imageId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminManagements.productimage'),
        ),
        migrations.AddField(
            model_name='products',
            name='resolution',
            field=models.IntegerField(default='543'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='refreshRate',
            field=models.ForeignKey(default='543', on_delete=django.db.models.deletion.CASCADE, to='adminManagements.refreshrate'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ForeignKey(default='543', on_delete=django.db.models.deletion.CASCADE, to='adminManagements.size'),
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
