# Generated by Django 5.1 on 2024-09-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0020_remove_products_imageid_products_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='refreshRate',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.RemoveField(
            model_name='refreshrate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='refreshrate',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.products')),
                ('refreshRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.refreshrate')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.size')),
            ],
        ),
    ]
