# Generated by Django 5.1 on 2024-09-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0022_varients_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varients',
            name='status',
        ),
    ]
