# Generated by Django 5.1 on 2024-09-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0023_remove_varients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='adminManagements.products'),
        ),
    ]
