# Generated by Django 5.1 on 2024-10-08 09:02

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupName',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='user',
            field=models.ManyToManyField(related_name='userChat', to=settings.AUTH_USER_MODEL),
        ),
    ]
