# Generated by Django 5.1 on 2024-10-11 17:25

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_remove_chatgroup_admin_alter_chatgroup_groupname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupName',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
