# Generated by Django 5.1 on 2024-10-18 04:58

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_alter_chatgroup_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupName',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
