# Generated by Django 5.1 on 2024-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_coupon_fixeddiscountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='fixedDiscountValue',
            field=models.FloatField(),
        ),
    ]
