# Generated by Django 5.1 on 2024-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_coupon_fixeddiscountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usedCount',
            field=models.IntegerField(default=0),
        ),
    ]
