# Generated by Django 5.1 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_coupon_usedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discountValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='fixedDiscountValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
