# Generated by Django 5.1 on 2024-09-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_coupon_discountvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discountType',
        ),
    ]
