# Generated by Django 5.1 on 2024-09-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_alter_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
    ]
