# Generated by Django 5.1 on 2024-09-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_remove_coupon_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='maxDiscountAmount',
            new_name='maxPurchaseAmount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicableBrand',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicableCategory',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicableProducts',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='fixedDiscountValue',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usageLimit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usedCount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validFrom',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
