# Generated by Django 5.1 on 2024-09-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('discounts', '0010_rename_maxdiscountamount_coupon_maxpurchaseamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('applicableBrand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brandoffer', to='adminManagements.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('applicableProducts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoffer', to='adminManagements.products')),
            ],
        ),
    ]
