# Generated by Django 5.1 on 2024-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_brandoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='discountValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discountValue',
            field=models.FloatField(),
        ),
    ]
