# Generated by Django 5.1 on 2024-09-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('userHome', '0002_alter_wishlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='fgdhfhg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.products')),
            ],
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
