# Generated by Django 5.1 on 2024-09-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('userHome', '0003_fgdhfhg_delete_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fgdhfhg',
            new_name='Wishlist',
        ),
    ]
