# Generated by Django 5.1 on 2024-09-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0004_rename_fgdhfhg_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='stock',
        ),
    ]
