# Generated by Django 5.1 on 2024-09-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('userHome', '0006_remove_wishlist_product_wishlist_varientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='varientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.varients'),
        ),
    ]
