# Generated by Django 5.1 on 2024-10-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0009_alter_wishlist_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
            ],
        ),
    ]
