# Generated by Django 5.1 on 2024-09-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0012_remove_productimage_croppedimage1_and_more'),
        ('shopping', '0002_alter_cart_userid_alter_cartitem_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.varients', unique=True),
        ),
    ]
