# Generated by Django 5.1 on 2024-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_order_orderstatus_alter_orderitem_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('awaiting_payment', 'Awaiting Payment')], default='pending', max_length=20),
        ),
    ]
