# Generated by Django 5.1 on 2024-09-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('shopping', '0010_remove_cartitem_product_remove_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='productId',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='adminManagements.products'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='varientId',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='adminManagements.varients'),
        ),
    ]
