# Generated by Django 5.1 on 2024-09-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagements', '0024_alter_varients_product'),
        ('shopping', '0013_orderitem_productid_orderitem_varientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.products'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='varientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminManagements.varients'),
        ),
    ]
