# Generated by Django 5.1 on 2024-09-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_orderitem_productid_alter_orderitem_varientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderId',
        ),
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, related_name='orderItemId', to='shopping.orderitem'),
        ),
    ]
