# Generated by Django 5.1 on 2024-09-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_alter_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderId',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='shopping.order'),
        ),
    ]
