# Generated by Django 5.1 on 2024-09-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_alter_order_orderitemid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItemId', to='shopping.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
    ]
