# Generated by Django 5.1 on 2024-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_alter_order_orderitemid_alter_order_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItemId',
        ),
        migrations.AddField(
            model_name='order',
            name='orderItemId',
            field=models.ManyToManyField(related_name='orderItemId', to='shopping.orderitem'),
        ),
    ]
