# Generated by Django 5.1 on 2024-09-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_alter_order_orderitemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItemId',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderItemId',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='orderItemId', to='shopping.order'),
        ),
    ]
