# Generated by Django 5.1 on 2024-09-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_alter_orderitem_orderitemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderItemId',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='orderItemId', to='shopping.order'),
        ),
    ]
