# Generated by Django 5.1 on 2024-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0031_order_cancelreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelReason',
            field=models.TextField(),
        ),
    ]
