# Generated by Django 5.1 on 2024-09-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0032_alter_order_cancelreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('awaiting_payment', 'Awaiting Payment'), ('refunded', 'Refunded')], default='dispatched', max_length=20),
        ),
    ]
