# Generated by Django 5.1 on 2024-09-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pamentId',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='signatreId',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('awaiting_payment', 'Awaiting Payment'), ('refunded', 'Refunded'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='dispatched', max_length=20),
        ),
    ]
