# Generated by Django 5.1 on 2024-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_order_pamentid_order_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pamentId',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='signatreId',
            field=models.CharField(),
        ),
    ]
