# Generated by Django 5.1 on 2024-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_alter_order_pamentid_alter_order_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
