# Generated by Django 5.1 on 2024-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0038_alter_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=678345),
        ),
    ]
