# Generated by Django 5.1 on 2024-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0040_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('cashOnDelivery', 'CashOnDelivey'), ('wallet', 'Wallet'), ('internetBanking', 'InternetBanking')], max_length=20),
        ),
    ]
