# Generated by Django 5.1 on 2024-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0043_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountAmount',
            field=models.FloatField(default=0),
        ),
    ]
