# Generated by Django 5.1 on 2024-10-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0044_order_discountamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discountAmount',
            new_name='discount',
        ),
    ]
