# Generated by Django 5.1 on 2024-10-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0045_rename_discountamount_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
