# Generated by Django 5.1 on 2024-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0047_order_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returnReason',
            field=models.TextField(default='sfds sf gfsg'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('returnRequested', 'Return Requested'), ('awaiting_payment', 'Awaiting Payment'), ('refunded', 'Refunded'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'Failed')], default='dispatched', max_length=20),
        ),
    ]
