# Generated by Django 5.1 on 2024-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0048_order_returnreason_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returnReason',
            field=models.TextField(),
        ),
    ]
