# Generated by Django 5.1 on 2024-10-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0049_alter_order_returnreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
