# Generated by Django 5.1 on 2024-10-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0050_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('returnRequested', 'Return Requested'), ('awaiting_payment', 'Awaiting Payment'), ('refunded', 'Refunded'), ('FAILURE', 'Failed')], default='dispatched', max_length=20),
        ),
    ]
